### ISSUE TITLE
Command `\Zbar' already defined.

### ISSUE THREAD

**Issue by Chenhao-Peng** [ChenjieGump/XJTU-BSThesis_latex_2022#1]
When compiling with Mac , faced with problem 
Command `[{
	"resource": "/usr/local/texlive/2022/texmf-dist/tex/latex/newtx/newtxmath.sty",
	"owner": "LaTeX",
	"severity": 8,
	"message": "Command `\\Zbar' already defined.",
	"source": "LaTeX",
	"startLineNumber": 928,
	"startColumn": 1,
	"endLineNumber": 928,
	"endColumn": 65536
}]

I solved this by simply delete the Line
`\DeclareMathSymbol{\Zbar}{\mathord}{lettersA}{94}`

**Comment by ChenjieGump** [comment]
Thanks for the help. Hope the graduation period goes well!
